spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        ddl-auto: true
        format_sql: true
  datasource:
    username: root
    password: {여러분들 비밀번호}
    url: jdbc:mysql://localhost:3306/{데이터베이스 이름}
    driver-class-name: com.mysql.cj.jdbc.Driver